name: deploy
run-name: "Terraform deploy (${{ github.ref_name }})"

on:
  push:
    tags: 
      - "*"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE: arn:aws:iam::944671670298:role/terraform-foundation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: aws-setup-ci-session

      - uses: hashicorp/setup-terraform@v4

      - name: Deploy Foundation
        working-directory: ./foundation
        run: |
          terraform init
          terraform plan -out=planout
          terraform apply planout
